export default
  {
    "nom": "Services",
    "name": "Services",
    "id": 0, 
    "selected":true,
    "desc": "Cliquer sur les carrés pleins pour découvrir l'arborescence. Cliquer sur les carrés vides pour découvrir les services et les inclure dans la liste sur la droite.",
    "color": '#305870',
    "children": [
        { "nom": "Démarrage","name": "Startup",
            "id": 1, "color":'rgb(255,127,14)',
            "descf": "Votre entreprise est sur le point d'éclore et vous être maintenant prêt à l'introduire au monde entier. Mais avez-vous ou maîtrisez-vous les outils essentiels à un bon démarrage? Voici quelques outils et services mis à votre disposition pour assurer un démarrage réussi : incorporation, plan d'affaire, plan comptable, etc...", 
            "desce": "Your company is about to open up and you are now ready to introduce it to the world. But do you have or master the essential tools for a good start? Here are some tools and services at your disposal to ensure a successful start: incorporation, business plan, accounting plan, etc.", 
            "selected":false,
            "children": [
                {   "id": 6,
                    "nom": "structure d'entreprise", "name": "enterprise structure", "color":'rgb(255,127,14)', "selected":false,
                    "descf": "Ensemble des règles de répartition de l'autorité, des tâches, de contrôle et de coordination. Une bonne structure est un gage de succès assuré.",
                    "desce": "Set of rules for the distribution of authority, tasks, control and coordination. A good structure is a guarantee of success."
                },
                {   "id": 7,
                    "nom": "incorporation", "name": "incorporation", "color":'rgb(255,127,14)',"selected":false,
                    "descf": "Une des étapes les plus importantes lors de la création de l'entreprise afin d'être conforme à la loi et de vous protéger en cas de litige.",
                    "desce": "One of the most important steps in setting up a company to comply with the law and protect you in the event of a dispute."
                },
                {   "id": 8,
                    "nom": "plan d'affaire", "name": "business plan", "color":'rgb(255,127,14)',"selected":false,
                    "descf": "La meilleure façon pour rassembler vos idées sur votre projet et de le communiquer aux autres. Nous savons comment les rédiger.",
                    "desce": "The best way to gather your ideas about your project and communicate it to others. We know how to write them."
                },
                {   "id": 9,
                    "nom": "plan comptable", "name": "accounting strategy", "color":'rgb(255,127,14)',"selected":false,
                    "descf": "Ou comment implanter une méthode rigoureuse de cueillette des données financiêres de l'entreprise et de maintenir cette même méthode tout au long des cycles de vie de l'entreprise.",
                    "desce": "Or how to implement a rigorous method of collecting the company's financial data and maintain this same method throughout the company's life cycles."
                },
                {   "id": 10,
                    "nom": "prévisions budgétaires", "name": "budget forecasts", "color":'rgb(255,127,14)', "color":'rgb(255,127,14)',"selected":false,
                    "descf": "C'est l'outil par excellence pour établir les objectifs financiers de votre entreprise.",
                    "desce": "It is the perfect tool to set your company's financial objectives."
                },
                {   "id": 11,
                    "nom": "recherche subventions", "name": "subsidies search", "color":'rgb(255,127,14)',"selected":false,
                    "descf": "Pour mieux vous aider à obtenir de que vous méritez en termes d'aide gouvernementale aux entreprises.",
                    "desce": "To better help you get what you deserve in terms of government assistance to businesses."
                },
                {   "id": 12,
                    "nom": "financement", "name": "financing", "color":'rgb(255,127,14)',"selected":false,
                    "descf": "Pour mieux vous aider à obtenir de que vous méritez en termes d'aide financière aux entreprises.",
                    "desce": "To better help you get what you deserve in terms of financial assistance to businesses."
                },
                {   "id": 13,
                    "nom": "plan de commercialisation", "name": "marketing plan", "color":'rgb(255,127,14)',"selected":false,
                    "descf": "Un outil efficace pour mieux connaître ce que le marché recherche dans votre créneau.",
                    "desce": "An effective tool to better understand what the market is looking for in your niche."
                },
            ]
        },
        { "nom": "Court terme", "name": "Short-term",
            "id": 2,"selected":false,"color":'rgb(44,160,44)',
            "descf": "Votre entreprise a le vent dans les voiles mais sa vitesse de croisière n'est pas au niveau de vos espérances (les problèmes sont difficilement identifiables et une consultation externe est requise). Les services que nous offront pour ce cycle pourront faire la différence entre la vitesse actuelle et une meilleure vitesse de croisiêre.",
            "desce": "Your company is on the move but its cruising speed is not up to your expectations (problems are difficult to identify and an external consultation is required). The services we offer for this cycle can make the difference between the current speed and a better cruising speed.",
            "children": [
                { "id": 14,"nom": "procédures de fin de mois","name": "month end procedures", 
                "descf": "Implantation systématique de vérification des transactions répartie en tâches et arrimage avec les prévisions budgétaire ci-haut mentionnés.",
                "desce": "Systematic implementation of transaction verification divided into tasks and alignment with the above-mentioned budget forecasts.",
                "color":'rgb(44,160,44)',"selected":false},
                { "id": 15,"nom": "gestion des ressources humaines","name": "human resource management", 
                "descf": "Pour les forces de chacun de cahcun de vos collaborateurs et maximiser leur potentiel. Connaître les forces de chacun pour mieux les répartir.",
                "desce": "For the strengths of each of your employees and maximize their potential. Know each other's strengths to better distribute them.","color":'rgb(44,160,44)',"selected":false},
                { "id": 16,"nom": "comparables budget vs réel","name": "actual vs. budget comparatives", 
                "descf": "Outil de mesure des écarts entre les prévisions antérieures et la réalité du moment afin d'apporter les corrections nécessaires.",
                "desce": "Tool for measuring the differences between previous forecasts and current reality in order to make the necessary corrections.",
                "color":'rgb(44,160,44)',"selected":false},
                { "id": 17,"nom": "analyse des ratios financiers","name": "financial ratio analysis", 
                "descf": "Outil de mesure des écarts entre les prévisions antérieures et la réalité du moment afin d'apporter les corrections nécessaires.",
                "desce": "Tool for measuring the differences between previous forecasts and current reality in order to make the necessary corrections.",
                "color":'rgb(44,160,44)',"selected":false},
                { "id": 18,"nom": "préparation des budgets annuels","name": "preparation of annual budgets", 
                "descf": "Outil de mesure des écarts entre les prévisions antérieures et la réalité du moment afin d'apporter les corrections nécessaires.",
                "desce": "Tool for measuring the differences between previous forecasts and current reality in order to make the necessary corrections.",
                "color":'rgb(44,160,44)',"selected":false}
            ]
        },
        { "nom": "Moyen terme" ,"name": "Medium-term" ,
            "id": 3,"selected":false,"color":'rgb(214,39,40)',
            "desce": "Une vision à long terme est maintenant nécessaire pour votre entreprise pour emprunter la voie de la pérennité. Que ce soit pour parer à un changement de garde soudain (plan de relève), vérifier l'état actuel de la situation (analyse des états financiers) ou améliorer les méthodes actuelles (analyse du prix de revient), nous proposons maintenant des outils spécialisés pour assurer la pérennité de votre entreprise.",
            "descf": "A long-term vision is now required for your company to move towards sustainability. Whether it is to deal with a sudden change of guard (succession plan), check the current state of the situation (analysis of financial statements) or improve current methods (cost price analysis), we now offer specialized tools to ensure the sustainability of your company.",
            "children": [
                { "id": 19,"nom": "révision structure financière","name": "financial structure revision",
                "descf":"Outil pour analyser en profondeur les cycles d'exploitation, d'investissement et de financement de votre entreprise.",
                "desce":"A tool for in-depth analysis of your company's operating, investment and financing cycles.",
                "color":'rgb(214,39,40)',"selected":false },
                { "id": 20,"nom": "analyse stratégique","name": "strategic analysis",
                "descf":"Processus d'analyse de la situation de votre entreprise ou d'un de vos domaines d'activité stratégique par rapport à votre environnement, votre marché, vos concurrents et leurs stratégies actuelles et potentielles dans le futur et ses capacités actuelles et futures.",
                "desce":"The process of analyzing the situation of your company or one of your strategic business areas in relation to your environment, your market, your competitors and their current and potential strategies in the future and its current and future capabilities.",
                "color":'rgb(214,39,40)',"selected":false },
                { "id": 21,"nom": "programme de réduction des coûts","name": "cost reduction program",
                "descf":"Implantation d'une méthode pour réduire sinon restreindre les coûts pour assurer un contrôle accru de vos opérations.",
                "desce":"Implementation of a method to reduce or even limit costs to ensure greater control of your operations.",
                "color":'rgb(214,39,40)',"selected":false },
                { "id": 22,"nom": "analyse rentabilité & efficacité","name": "efficiency and ROI analysis",
                "descf":"La rentabilité par l'efficacité: mise en place de jalons pour assurer le succès de votre entreprise.",
                "desce":"Profitability through efficiency: setting up milestones to ensure the success of your company.",
                "color":'rgb(214,39,40)',"selected":false },
                { "id": 23,"nom": "révision de la structure d'entreprise","name": "entreprise structure revision",
                "descf":"Revoir la structure d'entreprise mise en place lors du démarrage et corriger s'il y a lieu.",
                "desce":"Review the corporate structure put in place at the start up and correct if necessary.",
                "color":'rgb(214,39,40)',"selected":false },
                { "id": 24,"nom": "amélioration des processus continues","name": "continuous improvement process",
                "descf":"Comparer les processus actuels de votre entreprise avec des processus idéaux et les améliorer, le but étant de les améliorer continuellement.",
                "desce":"Compare your company's current processes with ideal processes and improve them, with the aim of continuously improving them.",
                "color":'rgb(214,39,40)',"selected":false },
                { "id": 25,"nom": "contrôles internes","name": "internal controls",
                "descf":"L'application ponctuelle des contrôles internes assure la maîtrise des opérations. Dans le cas extrême du redressement, on remplace les contrôles internes par les outils de redressement pour restructurer en profondeur.",
                "desce":"The punctual application of internal controls ensures the control of operations. In the extreme case of turnaround, internal controls are replaced by turnaround tools to restructure in depth.",
                "color":'rgb(214,39,40)',"selected":false },
                { "id": 26,"nom": "prix de revient","name": "costing",
                "descf":"Outil pour déterminer si votre entreprise est rentable et le niveau de rentabilité des chacun de vos produit et services.",
                "desce":"Tool to determine if your company is profitable and the level of profitability of each of your products and services.",
                "color":'rgb(214,39,40)',"selected":false }
            ]
        },
        { "nom": "Excellence" ,"name": "Excellence" ,
            "id": 4, "selected":false,"color":'rgb(148,103,189)',
            "descf": "Pas de temps pour la complaisance et inutile de s'asseoir sur ses lauriers. Même si tout semble bien aller, en est-il vraiment ainsi? Un survol rapide par notre équipe sur les modus operandi de votre entreprise nous permettront de trouver les failles existentes et optimer votre rendement. Une simple analyse des états financiers ou l'aplication d'un contrôle interne peut parfois révéler d'importantes lacunes au niveaux des méthodes et des opérations.",
            "desce": "No time for complacency and no need to rest on your laurels. Even if everything seems to be going well, is this really the case? A quick overview by our team on your company's modus operandi will allow us to find existing gaps and optimize your performance. A simple analysis of financial statements or the application of internal control may sometimes reveal significant deficiencies at the process and operational levels.",
            "children": [
                { "id": 27,"nom": "planification stratégique","name": "strategic planning",
                "descf":"Processus de développement de stratégies afin d'atteindre un objectif fixé.",
                "desce":"Process of developing strategies to achieve a set objective.",
                "color":'rgb(148,103,189)',"selected":false },
                { "id": 28,"nom": "plan de relève","name": "succession planning",
                "desc":"Une procédure qui garantit que l'organisation a suffisamment d'employés qualifiés pour répondre à ses objectifs stratégiques.",
                "desc":"A procedure that ensures that the organization has enough qualified employees to meet its strategic objectives.",
                "color":'rgb(148,103,189)',"selected":false },
                { "id": 29,"nom": "tableau de bord (scorecard)","name": "scorecard",
                "desc":"Méthode visant à mesurer les activités d'une entreprise selon les quatre perspectives principales.",
                "desc":"A method of measuring a company's activities from the four main perspectives",
                "color":'rgb(148,103,189)',"selected":false },
                { "id": 30,"nom": "analyse de la chaine des valeurs","name": "value chain optimisation",
                "desc":"Outil d’analyse stratégique permettant d’identifier, au sein d’une entreprise ou d’une organisation, les différentes activités clés créatrices de valeur pour le client et génératrices de marge pour l’entreprise.",
                "desc":"A strategic analysis tool that identifies, within a company or organization, the various key activities that create value for the customer and generate margin for the company.",
                "color":'rgb(148,103,189)',"selected":false },
                { "id": 31,"nom": "rigueur & discipline","name": "rigor & discipline",
                "desc":"Deux éléments essentiels à joindre à vos méthodes pour réaliser les objectifs de la planification stratégique.",
                "desc":"Two essential elements to be added to your methods to achieve the objectives of strategic planning.",
                "color":'rgb(148,103,189)',"selected":false },
                { "id": 32,"nom": "plans quinquennaux","name": "five-year plans",
                "desc":"Il sera plus facile de prévoir où votre entreprise sera dans cinq ans avec la mise en place de plans quinquennaux.",
                "desc":"It will be easier to predict where your business will be in five years with the implementation of five-year plans.",
                "color":'rgb(148,103,189)',"selected":false },
            ]
        },
        { "nom": "Redressement" ,"name": "Reengineering" ,
            "id": 5, "selected":false,"color":'rgb(140,86,75)',
            "descf": "Votre entreprise est en déclin et doit subir un redressement (problèmes fondamentaux liés à la structure de l'entreprise et les méthodes employées). Une application des services ci-dessous nous permettront de vous aider à redresser et remettre votre entreprise rapidement sur la voie du succès.",
            "desce": "Your company is in decline and in need of a turnaround (fundamental problems related to the company's structure and methods). An application of the services below will help us help you get your business back on track quickly and successfully.",
            "children": [
                { "id": 33,"nom": "respirateur artificiel", "name": "life support",
                "descf":"Processus pénible mais essentiel pour remettre votre entreprise en bonne santé.",
                "desce":"Tedious but essential process to get your business back in good health",
                "color":'rgb(140,86,75)',"selected":false },
                { "id": 34,"nom": "consolidation de dettes","name": "debt consolidation",
                "descf":"Connaître, préparer et consigner toutes les étapes de la consolidation dans un rapport détaillé.",
                "desce":"Know, prepare and record all steps of consolidation in a detailed report.",
                "color":'rgb(140,86,75)',"selected":false },
                { "id": 35,"nom": "recherche de nouveaux investisseurs","name": "search for new investors",
                "descf":"Poursuivre les étapes de redressement en recherchant de nouvelles sources de financement.",
                "desce":"Continue the recovery steps by seeking new sources of funding.",
                "color":'rgb(140,86,75)',"selected":false },
                { "id": 36,"nom": "réingénierie","name": "reengineering",
                "descf":"Trouver la cause profonde du déclin de l'entreprise et l'éliminer en repensant les processus d'affaires.", 
                "desce":"Find the root cause of the company's decline and eliminate it by rethinking business processes.", 
                "color":'rgb(140,86,75)',"selected":false },
                { "id": 37,"nom": "plan de revitalisation","name": "revitalization plan",
                "descf":"Approche moins radicale que la réingénierie permettant l'application de changements plus ou moins mineurs et rétablir ainsi la voie du succès.", 
                "desce":"Less radical than re-engineering, this approach allows for more or less minor changes to be applied and thus restores the path to success.", 
                "color":'rgb(140,86,75)',"selected":false },
                { "id": 38,"nom": "refinancement","name": "refinancing",
                "descf":"Offrir différents options de refinancement suite aux tâches précédentes de redressement ou de revitalisation.", 
                "desce":"Offer different refinancing options following previous recovery or revitalization tasks.", 
                "color":'rgb(140,86,75)',"selected":false },
            ]
        },
    ]
}